openapi: 3.0.3
info:
  title: Book Store APIs
  description: |-
    This is an APIs doc for book store systems.
    We only acheieve [book part](https://github.com/Tempoolu/bookstore_book) so far.
  contact:
    email: ludantong77@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
tags:
  - name: book
    description: Manager books
paths:
  /book:
    get:
      tags:
        - book
      summary: List all books
      description: List All books with details
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          description: Invalid status value
    post:
      tags:
        - book
      summary: Add a new book to the store
      description: Add a new book to the store
      requestBody:
        description: Create a new book to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'          
        '405':
          description: Invalid input
  /book/{bookId}:
    get:
      tags:
        - book
      summary: Find book by ID
      description: Returns a single book
      parameters:
        - name: bookId
          in: path
          description: ID of book to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Book not found
    put:
      tags:
        - book
      summary: Updates a book in the store with form data
      description: ''
      parameters:
        - name: bookId
          in: path
          description: ID of book that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
        - name: title
          in: query
          description: Title of book that needs to be updated
          schema:
            type: string
        - name: content
          in: query
          description: content of book that needs to be updated
          schema:
            type: string
      responses:
        '405':
          description: Invalid input
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          description: Title of a book
          example: How to read a book
        content:
          type: string
          description: Content of a book
          example: bla bla
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string
